name: Actualizar Firebase Futbol

on:
  schedule:
    # Se ejecuta al minuto 0 de cada hora
    - cron: '0 * * * *'
  workflow_dispatch: # Esto permite que tú le des al botón de "Ejecutar ahora"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script de extracción
        env:
          # Aquí conectamos el secreto de GitHub con tu código
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node index.js